include: package:very_good_analysis/analysis_options.yaml

# Regras adicionais customizadas
linter:
  rules:
    # Já excelente por padrão, mas vamos reforçar
    always_specify_types: false   # opcional, pode ser muito verboso
    avoid_dynamic_calls: true
    avoid_relative_lib_imports: true
    cancel_subscriptions: true
    close_sinks: true
    comment_references: true
    directives_ordering: true
    eol_at_end_of_file: true
    implicit_call_tearoffs: true
    missing_code_block_language_in_doc_comment: true
    no_adjacent_strings_in_list: true

    no_wildcard_variable_uses: true
    one_member_abstracts: false   # útil para repositórios
    only_throw_errors: true
    parameter_assignments: false
    prefer_final_locals: true
    prefer_relative_imports: false # usar imports absolutos com package:
    provide_deprecation_message: true
    sort_pub_dependencies: true
    test_types_in_equals: true
    throw_in_finally: false
    unnecessary_lambdas: true
    unnecessary_to_list_in_spreads: true
    use_enums: true
    use_super_parameters: true

analyzer:
  errors:
    invalid_annotation: ignore
    missing_required_param: error
    missing_return: error
    must_be_immutable: warning
    todo: ignore
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "lib/generated/**"
